# Generated by Django 4.2.2 on 2023-06-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='Asesor', max_length=55),
        ),
    ]
