# Generated by Django 4.2.3 on 2023-07-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_remove_customuser_rol_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_code",
            field=models.CharField(default="", max_length=55),
        ),
    ]
